# Generated by Django 4.0.5 on 2022-06-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('group', models.CharField(max_length=30)),
            ],
        ),
    ]
