# Generated by Django 4.0.5 on 2022-06-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Haircuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hand_FootCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
