# Generated by Django 4.0.5 on 2022-06-23 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_facial_haircuts_hand_footcare_delete_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facial',
            options={'verbose_name': 'Догляд за обличчям', 'verbose_name_plural': 'Догляд за обличчям'},
        ),
        migrations.AlterModelOptions(
            name='haircuts',
            options={'verbose_name': 'Стрижка', 'verbose_name_plural': 'Стрижки'},
        ),
        migrations.AlterModelOptions(
            name='hand_footcare',
            options={'verbose_name': 'Догляд за руками та ногами', 'verbose_name_plural': 'Догляд за руками та ногами'},
        ),
    ]
