# Generated by Django 4.0.5 on 2022-06-30 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_facial_discount_alter_haircuts_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facial',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='haircuts',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='hand_footcare',
            name='discount',
        ),
        migrations.AddField(
            model_name='facial',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=1800)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='haircuts',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=2400)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hand_footcare',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3000)),
            preserve_default=False,
        ),
    ]
